#' Check whether a tag from a bibtex exists in a set of existing content.
#'
#' @param bibtex_string a string of bibtex
#' @param existing_content a vector of strings to check against
#'
#' @return the existing content with the bibtex string appended if it does not already exist
#' @export
#'
#' @examples
#'
#' append_bibtex_string(bibtex_string = v_example_refs[2], existing_content = v_example_refs[1])
append_bibtex_string <- function(bibtex_string, existing_content){

  bib_tag <- extract_bibtex_tag(bibtex_string = bibtex_string)

  bib_tag_exists <- any(
    grepl(
      pattern = paste0("\\{", bib_tag, ","),
      x = existing_content
    )
  )

  if (!bib_tag_exists){
    if(!grepl(pattern = "^@.*?\\{([^,]+),.*", x = bibtex_string))
      bibtex_string <- NULL
    # Append new entry only if it does not already exist
    return(c(existing_content, " ", bibtex_string))
  } else {
    message("BibTeX tag ", bib_tag, " already exists in .bib file.")
    return(existing_content)
  }
}

#' Append the bibtex file for a series (vector of bibtex strings)
#'
#' If the tag already exists in the content then the bibtex string is ignored
#' otherwise it is incorporated into the content at the bottom, with a space between
#'
#' @param v_bibtex_strings a vector of bibtex strings
#' @param existing_content the existing content, generated by ReadLines in R on the .bib file.
#'
#' @return a vector of bibtex content
#' @export
#'
#' @examples
#'
append_bibtex_string_vec <- function(v_bibtex_strings, existing_content) {
  for (ref in v_bibtex_strings) {
    existing_content <- append_bibtex_string(
      bibtex_string = ref,
      existing_content = existing_content
    )
  }

  return(existing_content)
}
