#' Check whether a tag from a bibtex exists in a set of existing content.
#'
#' @param bibtex_entry a string of bibtex
#' @param existing_content a vector of strings to check against
#' @param verbose whether to print a message if the tag already exists
#'
#' @return the existing content with the bibtex string appended if it does not already exist
#'
#' @export
#'
#' @examples
#'
#' append_bibtex_entry(
#' bibtex_entry = v_example_refs[1],
#' existing_content = v_example_refs[1],
#' verbose = TRUE
#' )
#'
#' append_bibtex_entry(
#' bibtex_entry = v_example_refs[1],
#' existing_content = v_example_refs[1],
#' verbose = FALSE
#' )
append_bibtex_entry <- function(bibtex_entry,
                                 existing_content,
                                 verbose = FALSE){

  # Extract the tag from the bibtex string
  bib_tag <- extract_bibtex_tag(bibtex_entry = bibtex_entry)

  # Check if the tag already exists in the existing content
  bib_tag_exists <- any(
    grepl(
      pattern = paste0("\\{", bib_tag, ","),
      x = existing_content
    )
  )

  # If the tag does not exist, append the bibtex string
  if (all(!bib_tag_exists, !is.na(bib_tag))){
    if(!grepl(pattern = "^@.*?\\{([^,]+),.*", x = bibtex_entry)) {
      bibtex_entry <- NULL

      return(existing_content)
    }

    # Append new entry only if it does not already exist
    if(any(
      isTRUE(existing_content == ""),
      isTRUE(existing_content == " "),
      isTRUE(length(existing_content) == 0))) {

      return(bibtex_entry)
    } else {

      return(c(existing_content, " ", bibtex_entry))
    }
  } else if (is.na(bib_tag)) {

    return(existing_content)
  } else {
    # if it does exist, return the existing content and print a message
    if(verbose) message("BibTeX tag ", bib_tag, " already exists in .bib file. Using existing entry")

    return(existing_content)
  }
}

#' Append the bibtex file for a series (vector of bibtex strings)
#'
#' If the tag already exists in the content then the bibtex string is ignored
#' otherwise it is incorporated into the content at the bottom, with a space between
#'
#' @param v_bibtex_entries a vector of bibtex strings
#' @param existing_content the existing content, generated by ReadLines in R on the .bib file.
#' @param verbose whether to print messages to the console
#'
#' @return a vector of bibtex content
#' @export
#'
#' @examples
#'
#' append_bibtex_entry_vec(
#' v_bibtex_entries = v_example_refs[2],
#' existing_content = v_example_refs[1:5],
#' verbose = TRUE
#' )
#'
#' append_bibtex_entry_vec(
#' v_bibtex_entries = v_example_refs[1],
#' existing_content = v_example_refs[1:5],
#' verbose = FALSE
#' )
append_bibtex_entry_vec <- function(v_bibtex_entries,
                                     existing_content,
                                     verbose = FALSE) {

  # for each bibtex string, append it to the existing content with a space between
  for (ref in v_bibtex_entries) {
    existing_content <- append_bibtex_entry(
      bibtex_entry = ref,
      existing_content = existing_content,
      verbose = verbose
    )
  }

  return(existing_content)
}
